INSERT INTO clientes (nome, cidade) VALUES
('Alice', 'São Paulo'),
('Bruno', 'Rio de Janeiro'),
('Carla', 'Belo Horizonte'),
('Daniel', 'Curitiba'),
('Eduarda', 'Fortaleza'),
('Fernando', 'Porto Alegre'),
('Gabriela', 'Brasília'),
('Henrique', 'Salvador'),
('Isabela', 'Manaus'),
('João', 'Recife'),
('Karen', 'Goiânia'),
('Lucas', 'Natal'),
('Marina', 'Campinas'),
('Nathan', 'São José dos Campos'),
('Olivia', 'Maceió'),
('Paulo', 'Florianópolis'),
('Quintino', 'Cuiabá'),
('Rafaela', 'São Luís'),
('Samuel', 'Belém'),
('Tatiana', 'Aracaju'),
('Ubiratan', 'Vitória'),
('Vanessa', 'Ribeirão Preto'),
('William', 'Juiz de Fora'),
('Xavier', 'Campo Grande'),
('Yasmin', 'Joinville'),
('Zeca', 'Uberlândia'),
('Aline', 'Londrina'),
('Breno', 'Maringá'),
('Cátia', 'Santos'),
('Diego', 'Niterói'),
('Evelyn', 'Pelotas'),
('Felipe', 'Guarujá'),
('Giovanna', 'Jundiaí'),
('Hélio', 'Bauru'),
('Iara', 'Sorocaba'),
('Juliana', 'Volta Redonda'),
('Kevin', 'Osasco'),
('Larissa', 'Mogi das Cruzes'),
('Maurício', 'Teresina'),
('Natália', 'Macapá'),
('Otávio', 'Rio Branco'),
('Patrícia', 'Boa Vista'),
('Rodrigo', 'Anápolis'),
('Silvana', 'Barueri'),
('Tiago', 'Caxias do Sul'),
('Ursula', 'Taubaté'),
('Vinícius', 'Cabo Frio'),
('Wagner', 'São Carlos'),
('Yuri', 'Franca'),
('Adriana', 'Itu'),
('Bernardo', 'São Vicente'),
('Camila', 'Ipatinga'),
('Douglas', 'Parnamirim'),
('Erick', 'Sobral'),
('Fabiana', 'Caruaru'),
('Gabriel', 'Petrópolis'),
('Hugo', 'Itaboraí'),
('Ingrid', 'Foz do Iguaçu'),
('Jorge', 'São Gonçalo'),
('Kátia', 'Itapevi'),
('Leonardo', 'Paulista'),
('Melissa', 'Mossoró'),
('Nelson', 'Angra dos Reis'),
('Olga', 'Marília'),
('Pedro', 'Piracicaba'),
('Quésia', 'Patos de Minas'),
('Renato', 'Araraquara'),
('Sara', 'São José do Rio Preto'),
('Tereza', 'Itaquaquecetuba'),
('Ulisses', 'Várzea Grande'),
('Vera', 'Aparecida de Goiânia'),
('Walter', 'Carapicuíba'),
('Xênia', 'Bragança Paulista'),
('Yago', 'Lajeado'),
('Zilda', 'Presidente Prudente'),
('Alex', 'Crato'),
('Bianca', 'Rondonópolis'),
('César', 'Itabuna'),
('Daniela', 'Teófilo Otoni'),
('Edson', 'Catanduva'),
('Fátima', 'Guarapari'),
('Guilherme', 'Camaçari'),
('Heitor', 'Pará de Minas'),
('Ivone', 'Passo Fundo'),
('Jonathan', 'Pindamonhangaba'),
('Kelly', 'Aracati'),
('Luciana', 'Timóteo'),
('Marcos', 'Jequié'),
('Nádia', 'Catalão'),
('Oscar', 'Tupã'),
('Priscila', 'Erechim'),
('Rafael', 'Ubatuba'),
('Simone', 'Pouso Alegre'),
('Tomás', 'Três Corações'),
('Vicente', 'Tatuí'),
('Washington', 'Açailândia'),
('Ximena', 'Ourinhos'),
('Yasmin', 'Valinhos'),
('Zoraide', 'Nova Friburgo');
